--
-- TOC entry 3641 (class 0 OID 16417)
-- Dependencies: 217
-- Data for Name: Amenity; Type: TABLE DATA; Schema: public; Owner: iu
--

INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (1, 1, 'Towels');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (2, 1, 'Shampoo');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (3, 1, 'Soap');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (4, 1, 'Hairdryer');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (5, 1, 'Bathtub');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (6, 2, 'Oven');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (7, 2, 'Microwave');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (8, 2, 'Refrigerator');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (9, 2, 'Dishwasher');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (10, 2, 'Coffee Maker');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (11, 3, 'King Bed');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (12, 3, 'Queen Bed');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (13, 3, 'Twin Bed');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (14, 3, 'Bed Linens');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (15, 3, 'Wardrobe');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (16, 4, 'Sofa');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (17, 4, 'TV');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (18, 4, 'Coffee Table');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (19, 4, 'Bookshelf');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (20, 4, 'Fireplace');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (21, 5, 'Dining Table');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (22, 5, 'Chairs');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (23, 5, 'Tableware');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (24, 5, 'Wine Glasses');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (25, 5, 'Tablecloth');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (26, 6, 'BBQ Grill');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (27, 6, 'Patio Furniture');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (28, 6, 'Garden Swing');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (29, 6, 'Fire Pit');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (30, 6, 'Outdoor Lighting');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (31, 7, 'High-Speed Wi-Fi');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (32, 7, 'Printer');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (33, 7, 'Scanner');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (34, 7, 'Office Desk');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (35, 7, 'Office Chair');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (36, 8, 'Cable TV');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (37, 8, 'Home Theater');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (38, 8, 'Board Games');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (39, 8, 'Video Game Console');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (40, 8, 'DVD Collection');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (41, 9, 'Smoke Alarms');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (42, 9, 'Fire Extinguisher');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (43, 9, 'First Aid Kit');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (44, 9, 'Carbon Monoxide Detector');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (45, 9, 'Security Cameras');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (46, 10, 'Daily Housekeeping');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (47, 10, 'Laundry Service');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (48, 10, 'Dishwasher');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (49, 10, 'Trash Pickup');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (50, 10, 'Vacuum Cleaner');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (51, 11, 'Air Conditioning');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (52, 11, 'Central Heating');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (53, 11, 'Electric Fireplace');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (54, 11, 'Radiant Floor Heating');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (55, 11, 'Wood-Burning Stove');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (56, 12, 'Washer');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (57, 12, 'Dryer');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (58, 12, 'Iron');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (59, 12, 'Ironing Board');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (60, 12, 'Laundry Detergent');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (61, 13, 'Free Parking on Premises');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (62, 13, 'Street Parking');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (63, 13, 'Private Garage');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (64, 13, 'Carport');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (65, 13, 'Electric Vehicle Charging Station');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (66, 14, 'Outdoor Pool');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (67, 14, 'Indoor Pool');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (68, 14, 'Private Pool');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (69, 14, 'Infinity Pool');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (70, 14, 'Kiddie Pool');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (71, 15, 'Outdoor Hot Tub');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (72, 15, 'Indoor Hot Tub');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (73, 15, 'Jacuzzi');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (74, 15, 'Sauna');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (75, 15, 'Steam Room');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (76, 16, 'Private Gym');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (77, 16, 'Fitness Equipment');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (78, 16, 'Yoga Studio');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (79, 16, 'Treadmill');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (80, 16, 'Exercise Bike');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (81, 17, 'Building Elevator');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (82, 17, 'Private Elevator');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (83, 17, 'Wheelchair Accessible Elevator');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (84, 17, 'Service Elevator');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (85, 17, 'Freight Elevator');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (86, 18, 'Wheelchair Accessible Entrance');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (87, 18, 'Wheel-in Shower');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (88, 18, 'Grab Bars');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (89, 18, 'Disabled Parking Spot');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (90, 18, 'Wide Hallways');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (91, 19, 'Dog Friendly');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (92, 19, 'Cat Friendly');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (93, 19, 'Pet Deposit');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (94, 19, 'Pet Fee');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (95, 19, 'Pet Grooming Station');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (96, 20, 'High Chair');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (97, 20, 'Children''s Books and Toys');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (98, 20, 'Crib');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (99, 20, 'Baby Monitor');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (100, 20, 'Outlet Covers');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (101, 21, 'Smoking Permitted');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (102, 21, 'Smoking Area');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (103, 21, 'Cigar Friendly');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (104, 21, 'Pipe Friendly');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (105, 21, 'Vaping Allowed');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (106, 22, 'Event Space');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (107, 22, 'Party Equipment');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (108, 22, 'Dance Floor');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (109, 22, 'PA System');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (110, 22, 'Outdoor Stage');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (111, 23, 'Piano');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (112, 23, 'Guitar');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (113, 23, 'Violin');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (114, 23, 'Drums');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (115, 23, 'Saxophone');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (116, 24, 'Easels');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (117, 24, 'Canvas and Paints');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (118, 24, 'Sculpting Tools');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (119, 24, 'Pottery Wheel');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (120, 24, 'Sketchbooks');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (121, 25, 'Desk');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (122, 25, 'Office Chair');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (123, 25, 'Printer');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (124, 25, 'Scanner');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (125, 25, 'Whiteboard');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (126, 26, 'Secure Bike Storage');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (127, 26, 'Bike Racks');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (128, 26, 'Repair Stand');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (129, 26, 'Bike Lockers');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (130, 26, 'Indoor Bike Storage');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (131, 27, 'Billiards');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (132, 27, 'Table Tennis');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (133, 27, 'Video Game Console');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (134, 27, 'Board Games');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (135, 27, 'Foosball');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (136, 28, 'Flower Garden');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (137, 28, 'Vegetable Garden');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (138, 28, 'Zen Garden');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (139, 28, 'Playground');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (140, 28, 'Meditation Space');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (141, 29, 'Private Patio');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (142, 29, 'Shared Balcony');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (143, 29, 'Rooftop Terrace');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (144, 29, 'Garden Patio');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (145, 29, 'Oceanview Balcony');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (146, 30, 'Wood-Burning Fireplace');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (147, 30, 'Gas Fireplace');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (148, 30, 'Electric Fireplace');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (149, 30, 'Stone Fireplace');
INSERT INTO public."Amenity" (id, category_id, name) OVERRIDING SYSTEM VALUE VALUES (150, 30, 'Mantel and Hearth');

